/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.arcade.testproyecto;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import poo.clases.proyecto.Maquina;

/**
 *
 * @author erick cabezas
 */
public class FmrMenu extends javax.swing.JFrame {
    GUICobro cobro;
    DefaultTableModel dtmModelo;
    static ArrayList<Maquina> equiposAlquilados;
    /**
     * Creates new form FmrMenu
     */
    public FmrMenu() {
        initComponents();
        cobro=new GUICobro();
        //this.setExtendedState(MAXIMIZED_BOTH);
        dtmModelo= new DefaultTableModel(); // inicializamos el modelo de la tabla
        equiposAlquilados=new ArrayList<>();
        dtmModelo.addColumn("Equipo");
        dtmModelo.addColumn("Horas Alquiladas");
        dtmModelo.addColumn("Valor Por Hora");
        dtmModelo.addColumn("Valor Cobrado");
        tblCuenta.setModel(dtmModelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCuneta = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        lblCobrar = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuenta = new javax.swing.JTable();
        lblCobrototal = new javax.swing.JLabel();
        lblDolar = new javax.swing.JLabel();
        lblCobroTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Prinsipal");

        btnCuneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/payment_tax_invoice_calculator_icon_188745.png"))); // NOI18N
        btnCuneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCunetaActionPerformed(evt);
            }
        });

        btnCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/business-color_payment_icon-icons.com_53442.png"))); // NOI18N
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        lblCobrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCobrar.setText("Cobrar:");

        lblCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCuenta.setText("Cuenta:");

        tblCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCuenta);

        lblCobrototal.setText("Ingresos totales:");

        lblDolar.setForeground(new java.awt.Color(0, 102, 0));
        lblDolar.setText("$");

        lblCobroTotal.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lblCobroTotal.setText(".......");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblCobrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(lblCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCuneta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCobrototal)
                .addGap(24, 24, 24)
                .addComponent(lblCobroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDolar)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblCobrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblCuenta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnCobrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnCuneta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCobrototal)
                    .addComponent(lblDolar)
                    .addComponent(lblCobroTotal))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        // TODO add your handling code here:
        cobro.setVisible(true);
        
        
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btnCunetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCunetaActionPerformed
        // TODO add your handling code here:
        dtmModelo.setRowCount(0);
        for(Maquina eqp: equiposAlquilados){
            dtmModelo.addRow(new Object[]{eqp.toString(),eqp.getHorasDealquiler(),eqp.getValorPorHora()
            ,eqp.getCobrado()});
            
        }
        lblCobroTotal.setText(Double.toString(GUICobro.getCobroTotal()));
    }//GEN-LAST:event_btnCunetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnCuneta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCobrar;
    private javax.swing.JLabel lblCobroTotal;
    private javax.swing.JLabel lblCobrototal;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblDolar;
    private javax.swing.JTable tblCuenta;
    // End of variables declaration//GEN-END:variables
}
