package poo.arcade.testproyecto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;
import poo.clases.proyecto.Computadora;

/**
 *
 * @author Milton
 */
public class GUIComputadora extends javax.swing.JFrame {
Computadora computadora;
private double cobro;
GUICobro cobroT;
    /**
     * Creates new form GUIComputadora
     */
    public GUIComputadora() {
        initComponents();
        btnGuardarCobro.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbComputasoras = new javax.swing.JComboBox<>();
        lblTipoDeComputadora = new javax.swing.JLabel();
        lblHorasAlquiladas = new javax.swing.JLabel();
        txtHorasAlquiladas = new javax.swing.JTextField();
        btnCalcularpago = new javax.swing.JButton();
        btnGuardarCobro = new javax.swing.JButton();
        btnCancelarCobro = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Computadora"));

        cmbComputasoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computadora Gamer", "Computadora Oficina" }));
        cmbComputasoras.setSelectedIndex(-1);
        cmbComputasoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbComputasorasActionPerformed(evt);
            }
        });

        lblTipoDeComputadora.setText("Tipo De computadora");

        lblHorasAlquiladas.setText("Horas alquiladas:");

        btnCalcularpago.setText("Calcular Cobro");
        btnCalcularpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularpagoActionPerformed(evt);
            }
        });

        btnGuardarCobro.setText("Guardar Cobro");
        btnGuardarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCobroActionPerformed(evt);
            }
        });

        btnCancelarCobro.setText("Cancelar Cobro");
        btnCancelarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCobroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHorasAlquiladas)
                    .addComponent(lblTipoDeComputadora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbComputasoras, 0, 1, Short.MAX_VALUE)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtHorasAlquiladas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnCalcularpago)
                .addGap(30, 30, 30)
                .addComponent(btnGuardarCobro)
                .addGap(30, 30, 30)
                .addComponent(btnCancelarCobro)
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbComputasoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoDeComputadora))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorasAlquiladas)
                    .addComponent(txtHorasAlquiladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularpago)
                    .addComponent(btnGuardarCobro)
                    .addComponent(btnCancelarCobro))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbComputasorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbComputasorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbComputasorasActionPerformed

    private void btnCalcularpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularpagoActionPerformed
        // TODO add your handling code here:
        try{
            if(llenos()){
                int horasAlquiladas=Integer.parseInt(txtHorasAlquiladas.getText());
                String tipoDeCompu= (String) cmbComputasoras.getSelectedItem();
                bloquearCampos();
                computadora=new Computadora();
                computadora.setTipoDeComputadora(tipoDeCompu);
                computadora.setHorasDealquiler(horasAlquiladas);
                cobro=computadora.calcularPago();
                JOptionPane.showMessageDialog(rootPane,"valor a cobrar: "+cobro+"$"
                           ,"Cobro",JOptionPane.INFORMATION_MESSAGE);
                btnGuardarCobro.setEnabled(true);  
            }else{
                JOptionPane.showMessageDialog(rootPane,"llenar todos los campos","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane,"ingresar numeros eteros en Horas","ERROR",JOptionPane.ERROR_MESSAGE);
        }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(rootPane,"No se calculo el cobro","ERROR",JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"otro erros"+e.toString(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularpagoActionPerformed

    private void btnGuardarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCobroActionPerformed
        // TODO add your handling code here:
        GUICobro.setCobroTotal(cobro);
        FmrMenu.equiposAlquilados.add(computadora);
        llimpiar();
        btnGuardarCobro.setEnabled(false);
        desbloquearCampos();
        JOptionPane.showMessageDialog(rootPane,"cobro total  "+GUICobro.getCobroTotal()+"$","ERROR",JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btnGuardarCobroActionPerformed

    private void btnCancelarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCobroActionPerformed
        // TODO add your handling code here:
        llimpiar();
        desbloquearCampos();
        btnGuardarCobro.setEnabled(false);
    }//GEN-LAST:event_btnCancelarCobroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIComputadora().setVisible(true);
            }
        });
    }
public boolean llenos(){
    boolean txt1=txtHorasAlquiladas.getText().isEmpty();
        if(cmbComputasoras.getSelectedIndex()!=-1&&txt1!=true){
            return true;
        }else{
            return false;
        }
    }
public void llimpiar(){
    cmbComputasoras.setSelectedIndex(-1);
    txtHorasAlquiladas.setText(null);
}
public void bloquearCampos(){
    cmbComputasoras.setEnabled(false);
    txtHorasAlquiladas.setEnabled(false);
}
public void desbloquearCampos(){
    cmbComputasoras.setEnabled(true);
    txtHorasAlquiladas.setEnabled(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularpago;
    private javax.swing.JButton btnCancelarCobro;
    private javax.swing.JButton btnGuardarCobro;
    private javax.swing.JComboBox<String> cmbComputasoras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHorasAlquiladas;
    private javax.swing.JLabel lblTipoDeComputadora;
    private javax.swing.JTextField txtHorasAlquiladas;
    // End of variables declaration//GEN-END:variables
}
